### PR TITLE
Add Windows

### PR DESCRIPTION
**Pull request by jakirkham**
Attempts to build libcxxabi and libcxx on Windows as well. Unfortunately there is a CMake [configuration error]( https://ci.appveyor.com/project/jakirkham/libcxx-feedstock/build/1.0.28/job/rhv59sdnt5p6bvyl#L942 ). Have been unable to fix it yet, but imagine there is some patch that needs to be applied.

### CODE REVIEW

**Comment by isuruf** [comment]
the patch is for `libcxx`, but `libcxxabi` needs to patched as well.

**Comment by isuruf** [comment]
How about copying files from `Library/lib/cmake/` to `Library/lib/cmake/modules` and deleting at the end?

**Comment by jakirkham** [comment]
> the patch is for `libcxx`, but `libcxxabi` needs to patched as well.

I thought that too, but the `cmake` directory in `libcxxabi` only contains [one file]( https://ci.appveyor.com/project/jakirkham/libcxx-feedstock/build/1.0.29/job/x1pb9qj64u6oj1x4#L835 ). 😕 Not entirely sure why that was the case.

> How about copying files from `Library/lib/cmake/` to `Library/lib/cmake/modules` and deleting at the end?

That seems reasonable. We might be able to drop the patch in that case as well.

**Comment by isuruf** [comment]
That should have been `Library/lib/cmake/llvm` to `Library/lib/cmake/modules`

**Comment by jakirkham** [comment]
Feel free to push stuff to this branch directly if you like.

**Comment by jakirkham** [comment]
Replacing with PR ( https://github.com/conda-forge/libcxx-feedstock/pull/13 ).

**Pull request closed without merging**
